version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "javascript"
    groups:
      patch-and-minor:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "America/Sao_Paulo"
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      patch-and-minor:
        update-types:
          - "minor"
          - "patch"
